version: "3"

volumes:
  carhav_local_postgres_data: {}
  carhav_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: carhav_local_django
    container_name: carhav_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8006:8006"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: carhav_production_postgres
    container_name: carhav_local_postgres
    volumes:
      - carhav_local_postgres_data:/var/lib/postgresql/data:Z
      - carhav_local_postgres_data_backups:/backups:z
    ports:
      - "5433:5432"
    env_file:
      - ./.envs/.local/.postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5433
      POSTGRES_DB: carhav
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug

  # docs:
  #   image: carhav_local_docs
  #   container_name: carhav_local_docs
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./carhav:/app/carhav:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
