# Generated by Django 3.2.16 on 2022-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='courses', verbose_name='course_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='', upload_to='team', verbose_name='team_image'),
        ),
    ]
