# Generated by Django 3.2.16 on 2022-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221116_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
