# Generated by Django 3.2.16 on 2022-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221116_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='excerpt',
            field=models.TextField(default='enter an excerpt', help_text='Enter a brief description of the team member.', max_length=200),
            preserve_default=False,
        ),
    ]
