# Generated by Django 3.2.16 on 2022-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_team_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='excerpt',
            field=models.TextField(help_text='Enter a brief description of the team member.', max_length=20000),
        ),
    ]
