# Generated by Django 3.2.16 on 2022-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_team_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current',
            field=models.IntegerField(default=0, verbose_name='Current_student'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=255, verbose_name='Training duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='final_outcome',
            field=models.TextField(default='', verbose_name='Final outcome'),
        ),
        migrations.AddField(
            model_name='course',
            name='graduated',
            field=models.IntegerField(default=0, verbose_name='Graduated_student'),
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(default='', upload_to='courses', verbose_name='slide image 2'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', help_text='separate with comma e.g. Lagos, Abuja, Remote', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='course',
            name='side_image_1',
            field=models.ImageField(default='', upload_to='courses', verbose_name='Side Image 1'),
        ),
        migrations.AddField(
            model_name='course',
            name='side_image_2',
            field=models.ImageField(default='', upload_to='courses', verbose_name='Side Image 2'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(default='', verbose_name='Skills students will master'),
        ),
        migrations.AddField(
            model_name='course',
            name='trained_by',
            field=models.CharField(default='', help_text='separate with comma e.g. Amazon, CareerHaveen', max_length=255, verbose_name='Trained by'),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.CharField(default='', help_text='separate with comma', max_length=255, verbose_name='Trainers'),
        ),
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.IntegerField(default=0, verbose_name='Number_of_years'),
        ),
    ]
