# Generated by Django 3.2.16 on 2022-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_goals',
            field=models.TextField(default='', verbose_name='Project Goals'),
        ),
    ]
