# Generated by Django 3.2.16 on 2022-11-19 13:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usercourseapplicationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('image', models.ImageField(default='', upload_to='courses', verbose_name='course_image')),
                ('category', models.CharField(default='', max_length=100, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_link', models.CharField(default='', max_length=255, verbose_name='payment_link')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='email')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='phone')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('country_of_residence', models.CharField(default='', max_length=255, verbose_name='country_of_residence')),
                ('city_of_residence', models.CharField(default='', max_length=255, verbose_name='city_of_residence')),
                ('message', models.TextField(default='', verbose_name='message')),
                ('preparation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interview')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
