# Generated by Django 3.2.16 on 2022-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_interview_userinterviewschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(default='', upload_to='courses', verbose_name='image'),
        ),
    ]
