# Generated by Django 3.2.16 on 2022-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_interview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterviewschedule',
            name='resume',
            field=models.FileField(blank=True, default='', null=True, upload_to='resume/'),
        ),
    ]
