# Generated by Django 3.2.16 on 2022-11-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userinterviewschedule_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(default='', max_length=255, verbose_name='excerpt'),
        ),
    ]
