# Generated by Django 3.2.16 on 2022-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_course_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourseapplicationmodel',
            options={'verbose_name_plural': 'User Course/BootCamp Applications'},
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='duration',
            field=models.CharField(default='', max_length=255, verbose_name='Training duration'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='excerpt',
            field=models.TextField(default='', max_length=255, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='final_outcome',
            field=models.TextField(default='', verbose_name='Final outcome'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='location',
            field=models.CharField(default='', help_text='separate with comma e.g. Lagos, Abuja, Remote', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='project_goals',
            field=models.TextField(default='', verbose_name='Project Goals'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='skills',
            field=models.TextField(default='', verbose_name='Skills students will master'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='trained_by',
            field=models.CharField(default='', help_text='separate with comma e.g. Amazon, CareerHaveen', max_length=255, verbose_name='Trained by'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='trainer',
            field=models.CharField(default='', help_text='separate with comma', max_length=255, verbose_name='Trainers'),
        ),
        migrations.AddField(
            model_name='bootcampmodel',
            name='youtube_link',
            field=models.CharField(default='', help_text='enter a promotional video link', max_length=255, verbose_name='Youtube Link'),
        ),
    ]
