# Generated by Django 3.2.16 on 2022-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20221203_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', verbose_name='post_excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='post', verbose_name='post_image'),
        ),
    ]
